# watchtower — automatically update docker images on the internal server
# run alongside prod/docker-compose.yml
# checks for new image versions every 6 hours

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP:        "true"
      WATCHTOWER_POLL_INTERVAL:  21600   # 6 hours (in seconds)
      WATCHTOWER_LABEL_ENABLE:   "false" # update all running containers
      WATCHTOWER_INCLUDE_STOPPED: "false"
      WATCHTOWER_ROLLING_RESTART: "true"
      TZ: "America/New_York"
    command: --schedule "0 0 */6 * * *"
